### ISSUE TITLE
Awesome, let me know if you need help

### ISSUE THREAD

**Issue by RichardHightower** [garethahealy/camel-boon#1]

**Comment by garethahealy** [comment]
Created pull request: https://github.com/boonproject/boon/pull/301

**Comment by garethahealy** [comment]
Richard,

When you are happy/have time, can you do a release to the sonatype oss repo/mvn central (https://oss.sonatype.org/content/repositories/releases/io/fastjson/boon-bundle/)

I'll then update the version i am referencing from a snapshot built locally, to the release version.

Cheers.

**Comment by RichardHightower** [comment]
Its been released btw.

**Comment by garethahealy** [comment]
I can't see v0.32 yet - http://mvnrepository.com/artifact/io.fastjson/boon
